-- CATEGORIES

insert into categories (category) values ('motivating');
insert into categories (category) values ('Right-sized');
insert into categories (category) values ('Fully-configurable');
insert into categories (category) values ('focus group');
insert into categories (category) values ('array');
insert into categories (category) values ('Integrated');
insert into categories (category) values ('discrete');
insert into categories (category) values ('middleware');
insert into categories (category) values ('User-friendly');
insert into categories (category) values ('full-range');
insert into categories (category) values ('Future-proofed');
insert into categories (category) values ('Graphic Interface');
insert into categories (category) values ('help-desk');
insert into categories (category) values ('modular');
insert into categories (category) values ('multi-tasking');
insert into categories (category) values ('Profit-focused');
insert into categories (category) values ('time-frame');
insert into categories (category) values ('knowledge base');
insert into categories (category) values ('Multi-channelled');
insert into categories (category) values ('hierarchy');
insert into categories (category) values ('value-added');
insert into categories (category) values ('homogeneous');
insert into categories (category) values ('Persevering');
insert into categories (category) values ('tertiary');
insert into categories (category) values ('non-volatile');
insert into categories (category) values ('projection');
insert into categories (category) values ('Versatile');
insert into categories (category) values ('Seamless');
insert into categories (category) values ('Networked');
insert into categories (category) values ('capability');
insert into categories (category) values ('composite');
insert into categories (category) values ('knowledge user');
insert into categories (category) values ('Multi-lateral');
insert into categories (category) values ('clear-thinking');
insert into categories (category) values ('dynamic');
insert into categories (category) values ('high-level');
insert into categories (category) values ('migration');
insert into categories (category) values ('Multi-layered');
insert into categories (category) values ('application');
insert into categories (category) values ('Expanded');
insert into categories (category) values ('disintermediate');
insert into categories (category) values ('throughput');
insert into categories (category) values ('Centralized');
insert into categories (category) values ('bifurcated');
insert into categories (category) values ('Diverse');
insert into categories (category) values ('6th generation');
insert into categories (category) values ('Face to face');
insert into categories (category) values ('alliance');
insert into categories (category) values ('Progressive');
insert into categories (category) values ('infrastructure');

-- COMPANIES

insert into companies (vat_num, name, description, location, country, email, phone) values ('7813587766', 'Skimia', 'eco-centric', 'Nedryhayliv', 'Ukraine', 'vvallow0@vimeo.com', '634-727-5555');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2610452667', 'Abata', 'Cross-group', 'Vrýses', 'Greece', 'rbreznovic1@stanford.edu', '663-113-4452');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2999953534', 'Wordpedia', 'leading edge', 'Ddmashen', 'Armenia', 'tizhaky2@google.co.jp', '525-926-5296');
insert into companies (vat_num, name, description, location, country, email, phone) values ('9851249815', 'Wikido', 'asynchronous', 'Anávra', 'Greece', 'tkeuntje3@creativecommons.org', '679-725-7402');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1796614556', 'Dynava', 'logistical', 'Opatówek', 'Poland', 'mlitchmore4@digg.com', '824-582-7656');
insert into companies (vat_num, name, description, location, country, email, phone) values ('5606587963', 'Topicshots', 'encompassing', 'Tanbuqiao', 'China', 'cduffet5@independent.co.uk', '722-353-8592');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7067422582', 'Avaveo', 'clear-thinking', 'Metz', 'France', 'wkleimt6@cbsnews.com', '306-182-2384');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1099373239', 'Oyondu', 'Enhanced', 'Shīnḏanḏ', 'Afghanistan', 'lpankettman7@fema.gov', '764-159-4627');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2715862318', 'Edgeify', 'Multi-channelled', 'Agualva de Cima', 'Portugal', 'rgrumley8@blogspot.com', '380-280-7862');
insert into companies (vat_num, name, description, location, country, email, phone) values ('0342697676', 'Jayo', 'fault-tolerant', 'Vårby', 'Sweden', 'ssollitt9@ycombinator.com', '666-129-2601');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1742863477', 'Einti', 'upward-trending', 'Kavajë', 'Albania', 'rsothebya@reference.com', '333-340-6333');
insert into companies (vat_num, name, description, location, country, email, phone) values ('9360613681', 'Kwilith', 'responsive', 'Luobei', 'China', 'mjammesb@baidu.com', '995-255-6941');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7905717178', 'Dablist', 'secondary', 'Tula', 'Russia', 'cgowersc@ask.com', '345-270-3885');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4314625333', 'Pixope', 'De-engineered', 'Longsheng', 'China', 'hludlowd@shinystat.com', '218-479-9470');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4235415662', 'Vinder', 'Proactive', 'Sumberngerjat', 'Indonesia', 'gmacritchiee@hao123.com', '260-313-6346');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4279571821', 'Midel', 'Focused', 'Ambarawa', 'Indonesia', 'gdorief@webs.com', '488-143-7534');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7419968853', 'Tagopia', 'firmware', 'Golubac', 'Serbia', 'pjoostg@e-recht24.de', '590-678-6903');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7379995022', 'Aibox', 'installation', 'Bochum', 'Germany', 'creglarh@mlb.com', '260-495-4990');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7833389226', 'Youtags', 'data-warehouse', 'Taubaté', 'Brazil', 'shedoni@scribd.com', '779-290-8390');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7746657621', 'Ailane', 'functionalities', 'Souflí', 'Greece', 'hbudleighj@nih.gov', '512-377-0247');
insert into companies (vat_num, name, description, location, country, email, phone) values ('0682055921', 'Zoomcast', 'time-frame', 'Cimanggu', 'Indonesia', 'npeatk@seattletimes.com', '398-289-9778');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1288909284', 'Zoonder', 'Down-sized', 'Reinaldes', 'Portugal', 'rdawidowitzl@prnewswire.com', '453-217-9561');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7878329613', 'Quimba', 'Distributed', 'Sumberan', 'Indonesia', 'jjacquesm@dyndns.org', '705-736-9126');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2968308947', 'Dabvine', 'modular', 'Jajawai', 'Indonesia', 'ewollacottn@nature.com', '834-376-8716');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2191480322', 'Livetube', 'Balanced', 'Citangtu Kaler', 'Indonesia', 'bgenno@phpbb.com', '475-454-5577');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6550811856', 'Divanoodle', 'capability', 'Concepción', 'Colombia', 'egowrichp@facebook.com', '112-941-4321');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3971561969', 'Skiba', 'reciprocal', 'Dengjiang', 'China', 'ljagsonq@naver.com', '776-254-6348');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1539308723', 'Rhycero', 'hybrid', 'El Bauga', 'Sudan', 'pcominottir@devhub.com', '279-135-7110');
insert into companies (vat_num, name, description, location, country, email, phone) values ('0214879240', 'Dynazzy', 'Synchronised', 'Cuchumbaya', 'Peru', 'rbrodbins@wix.com', '486-608-8344');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6312115410', 'Meevee', 'Pre-emptive', 'Santa Bárbara', 'Guatemala', 'mfishleet@baidu.com', '432-734-0214');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1392362989', 'Mynte', 'asynchronous', 'Helong', 'China', 'wgoncavesu@hostgator.com', '123-105-5064');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2866984420', 'Fivechat', 'Reduced', 'Al Ḩawātah', 'Sudan', 'smuskv@deviantart.com', '132-111-0024');
insert into companies (vat_num, name, description, location, country, email, phone) values ('8000468069', 'Devbug', 'Sharable', 'Salto', 'Argentina', 'cpedroniw@sakura.ne.jp', '824-781-9901');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2026685207', 'Skyndu', 'synergy', 'Anju', 'North Korea', 'dbuttrickx@salon.com', '515-150-1762');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4815036438', 'Voomm', 'neutral', 'Brzeszcze', 'Poland', 'cmcmahony@networkadvertising.org', '100-394-4950');
insert into companies (vat_num, name, description, location, country, email, phone) values ('8251667054', 'Skajo', 'hybrid', 'Malicboy', 'Philippines', 'colunnyz@creativecommons.org', '204-647-3465');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6481684293', 'Topiczoom', 'leading edge', 'Alcains', 'Portugal', 'azelland10@simplemachines.org', '410-981-7807');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2882013035', 'Oba', 'Integrated', 'Kaniv', 'Ukraine', 'nverry11@unicef.org', '397-902-3257');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3735388493', 'Avavee', 'Business-focused', 'Kankan', 'Guinea', 'rbuxey12@wikipedia.org', '891-234-3206');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4904056450', 'Fadeo', 'Switchable', 'Huochezhan', 'China', 'vvanniekerk13@so-net.ne.jp', '521-160-8802');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2964230730', 'Abatz', 'cohesive', 'Stepanovićevo', 'Serbia', 'mobin14@msu.edu', '225-628-8992');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7358642309', 'Eamia', 'cohesive', 'Chimtāl', 'Afghanistan', 'abroxholme15@csmonitor.com', '617-523-3479');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2903668647', 'Flipstorm', 'infrastructure', 'San Agustín Acasaguastlán', 'Guatemala', 'cmeeron16@foxnews.com', '179-408-2387');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7946997930', 'Blognation', 'open system', 'Tegina', 'Nigeria', 'kblose17@tiny.cc', '902-955-2690');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1428347429', 'Skiba', '6th generation', 'Bor Tungge', 'China', 'dbridal18@ucoz.com', '935-270-6564');
insert into companies (vat_num, name, description, location, country, email, phone) values ('8806207407', 'Voonix', 'exuding', 'Alingsås', 'Sweden', 'dsummons19@purevolume.com', '565-399-7223');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2028497688', 'Innotype', 'hierarchy', '‘Arīqah', 'Syria', 'skliemchen1a@gov.uk', '169-123-0467');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6924683347', 'Blogpad', 'Total', 'Chixi', 'China', 'lbohike1b@mapquest.com', '204-616-3786');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6389202679', 'Jabbertype', 'Mandatory', 'Neftekamsk', 'Russia', 'jemanuelov1c@jiathis.com', '478-547-6417');
insert into companies (vat_num, name, description, location, country, email, phone) values ('5583021918', 'Mydo', 'disintermediate', 'Shigou', 'China', 'mlangan1d@dagondesign.com', '201-447-4593');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3171161443', 'Innotype', 'national', 'Babagan', 'Indonesia', 'edowning1e@soundcloud.com', '801-222-6391');
insert into companies (vat_num, name, description, location, country, email, phone) values ('7097118857', 'Demivee', 'Ameliorated', 'Sauri', 'Nigeria', 'jfairs1f@skype.com', '267-405-1487');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3625485222', 'Skippad', 'Decentralized', 'Boucinha', 'Portugal', 'iwoodgate1g@weibo.com', '882-880-7051');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6118018391', 'Blogpad', 'Advanced', 'Torzhok', 'Russia', 'tplows1h@angelfire.com', '523-647-4917');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2033969169', 'Quatz', 'Realigned', 'Oliveiras', 'Portugal', 'dhargreave1i@e-recht24.de', '468-617-9071');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3668896208', 'Abatz', 'systemic', 'Ōdachō-ōda', 'Japan', 'gbackshell1j@netscape.com', '735-482-9198');
insert into companies (vat_num, name, description, location, country, email, phone) values ('5050696275', 'Wikizz', 'composite', 'Sorang', 'Kazakhstan', 'spavlik1k@ebay.co.uk', '872-535-3215');
insert into companies (vat_num, name, description, location, country, email, phone) values ('4866518235', 'Browsebug', 'secured line', 'Soanierana Ivongo', 'Madagascar', 'jstrachan1l@canalblog.com', '825-940-5615');
insert into companies (vat_num, name, description, location, country, email, phone) values ('9741347960', 'Browsecat', 'functionalities', 'Bastak', 'Iran', 'dcuckson1m@thetimes.co.uk', '351-398-4571');
insert into companies (vat_num, name, description, location, country, email, phone) values ('8315030922', 'Nlounge', 'incremental', 'Ocho Rios', 'Jamaica', 'bpilch1n@youku.com', '411-464-4311');
insert into companies (vat_num, name, description, location, country, email, phone) values ('8931360991', 'Thoughtbridge', 'Stand-alone', 'Changyanbao', 'China', 'bratcliff1o@latimes.com', '293-633-2731');
insert into companies (vat_num, name, description, location, country, email, phone) values ('0522409342', 'Meedoo', 'Down-sized', 'Palmeira', 'Brazil', 'rskews1p@un.org', '505-739-6964');
insert into companies (vat_num, name, description, location, country, email, phone) values ('2300335271', 'Leexo', 'Streamlined', 'Cañazas', 'Panama', 'kpetford1q@google.es', '905-197-5442');
insert into companies (vat_num, name, description, location, country, email, phone) values ('1813906203', 'Pixope', 'system-worthy', 'Kalisabuk', 'Indonesia', 'bflarity1r@berkeley.edu', '440-827-9911');
insert into companies (vat_num, name, description, location, country, email, phone) values ('6592480866', 'Mybuzz', 'internet solution', 'K Bang', 'Vietnam', 'bwetherby1s@usnews.com', '194-287-5020');
insert into companies (vat_num, name, description, location, country, email, phone) values ('3882785519', 'Zoonder', 'bandwidth-monitored', 'Meilisi', 'China', 'nlavielle1t@uol.com.br', '697-657-6693');
insert into companies (vat_num, name, description, location, country, email, phone) values ('5717993455', 'Centidel', 'homogeneous', 'Caen', 'France', 'athompson1u@un.org', '344-602-2329');
insert into companies (vat_num, name, description, location, country, email, phone) values ('0743869265', 'Dabvine', 'Monitored', 'Nepomuceno', 'Brazil', 'chanks1v@rediff.com', '146-580-9194');

-- JOB OFFERS

insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (1, 0, 'VP Accounting', 'Gastric contents in bronchus causing oth injury, subs encntr', '2021-09-28 13:44:07', 'Mont-de-Marsan', 3);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (2, 0, 'Marketing Assistant', 'Puncture wound w foreign body of oth part of head, sequela', '2022-09-18 14:37:39', 'El Paso', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (3, 0, 'Dental Hygienist', 'Nondisp spiral fx shaft of r femr, 7thP', '2021-07-03 13:22:19', 'San Jose', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (4, 0, 'VP Accounting', 'Burn of third degree of left hand, unsp site, subs encntr', '2021-07-09 11:43:52', 'Nanganumba', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (5, 0, 'Nuclear Power Engineer', 'Calcifcn and ossifictn of muscles assoc w burns, oth site', '2022-04-09 16:34:51', 'Duogongma', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (6, 0, 'Chief Design Engineer', 'Corrosion of first degree of left forearm, sequela', '2022-06-07 03:31:10', 'Cipondok', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (7, 1, 'Mechanical Systems Engineer', 'Corrosion of first degree of nose (septum), init encntr', '2022-07-30 02:55:18', 'Kolor', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (8, 0, 'Environmental Tech', 'Nondisp comminuted fracture of shaft of ulna, left arm, init', '2021-01-20 01:54:45', 'Aqsay', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (9, 0, 'Geologist III', 'Alcohol use complicating childbirth', '2022-05-17 15:11:46', 'Traganón', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (10, 0, 'Dental Hygienist', 'Corrosion of unspecified degree of right axilla', '2021-12-18 05:29:44', 'Kwolla', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (11, 0, 'Account Executive', 'Other bilateral secondary osteoarthritis of knee', '2022-05-13 04:53:48', 'Pagaden', 6);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (12, 1, 'Civil Engineer', 'Peripheral T-cell lymphoma, not classified, nodes mult site', '2023-01-23 01:18:31', 'Weixin', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (13, 1, 'Staff Scientist', 'Driver of hv veh injured in clsn w 2/3-whl mv in traf, subs', '2022-11-18 23:16:40', 'Nantes', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (14, 1, 'Senior Developer', 'Blister (nonthermal) of abdominal wall', '2022-04-18 05:45:17', 'Botoh', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (15, 1, 'Data Coordiator', 'Other marginal perforations of tympanic membrane, right ear', '2021-04-10 01:45:40', 'Parintins', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (16, 0, 'Actuary', 'Oth osteopor w current pathological fracture, unsp ank/ft', '2021-01-16 12:01:34', 'Mkiriwadjumoi', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (17, 0, 'Geological Engineer', 'Poisoning by sulfonamides, undetermined, sequela', '2022-12-27 20:22:59', 'Jacksonville', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (18, 0, 'Chemical Engineer', 'Fall from motorized mobility scooter, sequela', '2022-01-26 08:48:29', 'Zamora', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (19, 1, 'Systems Administrator I', 'Path fx in neopltc dis, left rad, subs for fx w delay heal', '2022-05-15 01:05:47', 'Mandor', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (20, 0, 'Research Associate', 'Unsp inj msl/tnd lng extn msl toe at ank/ft lev,unsp ft,sqla', '2021-12-12 16:54:37', 'Vnorovy', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (21, 1, 'Technical Writer', 'Sltr-haris Type I physl fx upr end rad, l arm, 7thG', '2021-02-19 17:50:02', 'Porto Seguro', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (22, 0, 'Web Developer II', 'Laceration w fb of unsp lesser toe(s) w damage to nail', '2023-01-23 07:09:13', 'Libertad', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (23, 1, 'Sales Representative', 'Pressure ulcer of sacral region', '2021-11-19 07:57:54', 'Al Miftāḩ', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (24, 0, 'GIS Technical Architect', 'Nondisp suprcndl fx w/o intrcndl extn low end unsp femr,7thF', '2022-04-04 05:28:11', 'Otyniya', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (25, 0, 'Structural Analysis Engineer', 'Rat-bite fever, unspecified', '2022-06-06 10:31:08', 'Vyzhnytsya', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (26, 1, 'Statistician IV', 'Unsp open wound of right great toe w damage to nail, subs', '2021-02-12 09:55:14', 'Leluo', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (27, 0, 'Associate Professor', 'Absence and agenesis of lacrimal apparatus', '2021-01-31 06:00:30', 'Anse à Galets', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (28, 1, 'Account Representative IV', 'Bucket-handle tear of medial meniscus, current injury', '2023-01-21 20:45:50', 'Nanshe', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (29, 0, 'Programmer IV', 'Pedl cyc driver inj in nonclsn trnsp acc in traf, sequela', '2021-09-09 01:25:22', 'Kajuru', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (30, 1, 'Electrical Engineer', 'Maternal care for disproportion due to oth fetal deformities', '2021-05-26 09:08:30', 'Ningmute', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (31, 1, 'Nurse', 'Injury of ulnar nerve at wrs/hnd lv of unsp arm, init', '2022-06-20 05:55:44', 'Donghai', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (32, 0, 'Technical Writer', 'Antepart hemorrhage w dissem intravasc coag, first trimester', '2022-05-25 07:34:30', 'Hengelo', 6);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (33, 1, 'Assistant Media Planner', 'Self-harm by drown while in swimming pool, sequela', '2021-12-30 03:03:58', 'Nabire', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (34, 0, 'Graphic Designer', 'Nondisp fx of distal phalanx of right thumb, init', '2021-09-02 12:25:27', 'Chumikan', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (35, 1, 'Nurse Practicioner', 'Central serous chorioretinopathy', '2022-01-29 09:07:02', 'Faeanak Dua', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (36, 1, 'Accounting Assistant I', 'Oth physl fx upr end humer, left arm, subs for fx w nonunion', '2021-01-20 03:27:29', 'Jakšić', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (37, 1, 'Web Developer II', 'Cocaine dependence with cocaine-induced psychotic disorder', '2021-01-14 19:47:12', 'Shenglilu', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (38, 1, 'Quality Control Specialist', 'Inj msl/fasc/tnd posterior grp at thi lev, right thigh, subs', '2022-06-24 04:29:39', 'Miami', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (39, 0, 'Mechanical Systems Engineer', 'Juvenile rheumatoid arthritis w systemic onset, left ank/ft', '2021-09-10 11:07:05', 'Sumurgayam', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (40, 0, 'Payment Adjustment Coordinator', 'Ped w convey injured in clsn w pedl cyc in traf, sequela', '2022-07-12 00:11:47', 'Pendolo', 3);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (41, 0, 'Nuclear Power Engineer', 'Nondisp bicondylar fx l tibia, 7thE', '2021-07-31 09:40:19', 'Mbale', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (42, 0, 'Professor', 'Laceration w fb of thmb w/o damage to nail, sequela', '2021-12-12 10:06:36', 'Seattle', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (43, 1, 'Environmental Tech', 'Malaria due to simian plasmodia', '2021-05-02 15:08:32', 'Corga', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (44, 0, 'Statistician IV', 'Corrosion of third degree of shoulder', '2022-08-18 13:12:46', 'Campos Novos', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (45, 0, 'Paralegal', 'Contus/lac/hem brainstem w/o loss of consciousness, init', '2022-07-13 22:27:51', 'Tampekan', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (46, 1, 'Graphic Designer', 'Disp fx of med phalanx of l mid fngr, subs for fx w malunion', '2021-04-02 08:50:51', 'Chicago', 6);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (47, 1, 'Product Engineer', 'Type 1 diabetes mellitus with neurological complications', '2023-01-15 18:30:09', 'Szamotuły', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (48, 0, 'Safety Technician I', 'Corros 60-69% of body surface w 30-39% third degree corros', '2022-03-23 23:11:23', 'Ropcha', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (49, 1, 'Budget/Accounting Analyst I', 'Spasmodic torticollis', '2022-07-01 23:01:04', 'Fantino', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (50, 0, 'Cost Accountant', 'Lac w/o fb of right great toe w/o damage to nail, init', '2022-07-18 07:18:02', 'Debar', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (51, 1, 'Research Assistant IV', 'Laceration with foreign body of larynx, subsequent encounter', '2022-07-17 20:20:51', 'San Carlos', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (52, 1, 'Junior Executive', 'Contact with workbench tool, subsequent encounter', '2022-01-28 10:45:36', 'Kímolos', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (53, 1, 'Senior Developer', 'Laceration w/o fb of unsp great toe w damage to nail', '2022-11-27 17:06:04', 'Minneapolis', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (54, 0, 'Assistant Professor', 'Diphyllobothriasis and sparganosis', '2022-07-10 13:59:20', 'Rungkang', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (55, 0, 'Office Assistant III', 'Concussion and edema of thoracic spinal cord, init encntr', '2022-01-02 17:34:11', 'Yuzui', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (56, 1, 'Executive Secretary', 'Occ of pk-up/van inj in trnsp acc w miltry vehicle, sequela', '2023-01-22 22:26:58', 'Budva', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (57, 1, 'Registered Nurse', 'Person injured in collision betw car and bus, nontraf, subs', '2021-10-30 09:13:51', 'Quimper', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (58, 0, 'Dental Hygienist', 'Nondisp fx of olecran pro w/o intartic extn r ulna, 7thN', '2021-01-20 00:02:05', 'Ulapes', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (59, 0, 'Recruiter', 'Nondisp apophyseal fx right femur, init for opn fx type I/2', '2021-06-15 23:27:59', 'Samayac', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (60, 1, 'Legal Assistant', 'Strain of musc/fasc/tend prt biceps, left arm, sequela', '2022-01-08 12:02:27', 'Briey', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (61, 0, 'Administrative Assistant III', 'Blastomycotic meningoencephalitis', '2023-01-06 18:58:37', 'Fuente de Oro', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (62, 0, 'Health Coach III', 'Disp fx of base of nk of unsp femr, 7thK', '2021-06-10 21:09:13', 'Jiaoxie', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (63, 1, 'Geologist IV', 'Placentitis, third trimester, fetus 1', '2022-11-28 10:32:11', 'Songkhla', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (64, 0, 'GIS Technical Architect', 'Generalized contraction of visual field, left eye', '2022-01-21 12:06:34', 'Ilioúpoli', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (65, 0, 'GIS Technical Architect', 'Sltr-haris Type II physl fx low end humer, unsp arm, 7thG', '2022-06-06 11:41:57', 'Esperanza', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (66, 0, 'Marketing Manager', 'Frostbite with tissue necrosis of knee and lower leg', '2022-11-29 21:12:22', 'Itaitinga', 10);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (67, 1, 'Information Systems Manager', 'Burn of second degree of unsp thumb (nail), subs encntr', '2022-07-25 09:28:23', 'Dao’er', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (68, 1, 'Quality Control Specialist', 'Sltr-haris Type III physeal fx right metatarsal, 7thB', '2021-01-25 08:09:43', 'Talavera', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (69, 1, 'Research Nurse', 'Nondisp fx of med phalanx of l idx fngr, 7thP', '2022-12-27 18:33:08', 'Chmielno', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (70, 1, 'Nurse', 'Exposure to flames in controlled fire in bldg', '2021-06-06 15:09:45', 'Chame', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (71, 1, 'Marketing Manager', 'Angiodysplasia of colon', '2022-04-10 08:30:10', 'Demir Hisar', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (72, 0, 'Environmental Specialist', 'Other fracture of occiput, left side, 7thK', '2021-06-28 03:59:51', 'Santa Eulalia', 3);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (73, 0, 'Speech Pathologist', 'Other specified injuries of lower back, initial encounter', '2022-03-25 00:34:30', 'Dar Chabanne', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (74, 0, 'Senior Sales Associate', 'Open bite of unsp frnt wall of thrx w/o penet thor cav, sqla', '2021-10-02 23:33:25', 'La Mesa', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (75, 1, 'Research Associate', 'Idiopathic gout, unspecified ankle and foot', '2021-12-11 03:58:45', 'Hostos', 3);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (76, 1, 'Technical Writer', 'Other physeal fracture of left metatarsal, 7thP', '2023-01-12 07:07:17', 'Puubheto', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (77, 0, 'Director of Sales', 'Disloc of prox interphaln joint of r little finger, sequela', '2022-11-24 17:27:54', 'Xiehu', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (78, 1, 'VP Marketing', 'Adverse effect of succinimides and oxazolidinediones', '2021-01-22 05:56:25', 'Xihe', 7);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (79, 1, 'Account Coordinator', 'Puncture wound with foreign body of unsp breast, subs encntr', '2022-12-22 21:33:45', 'Chaínça', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (80, 1, 'Geological Engineer', 'Unsp bus occupant injured in collision w unsp mv nontraf', '2022-02-17 07:45:50', 'Novhorodka', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (81, 1, 'Clinical Specialist', 'Primary blast injury of thoracic trachea', '2021-10-13 17:01:39', 'As Suwaydā’', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (82, 0, 'Senior Quality Engineer', 'Corrosion of other parts of alimentary tract, init encntr', '2021-12-10 20:19:22', 'Betioky', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (83, 1, 'Help Desk Technician', 'Malignant neoplasm of right acoustic nerve', '2022-04-07 08:47:49', 'Paraparaumu', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (84, 1, 'Paralegal', 'Reiter''s disease, ankle and foot', '2021-06-24 06:24:39', 'Villa Serrano', 6);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (85, 1, 'Human Resources Assistant III', 'Insect bite (nonvenomous) of breast, left breast', '2022-01-30 01:13:06', 'Yashio-shi', 9);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (86, 0, 'Tax Accountant', 'Poisoning by thrombolytic drug, assault', '2022-11-26 20:11:04', 'Krasica', 4);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (87, 0, 'Environmental Tech', 'Athscl heart disease of native cor art w ang pctrs w spasm', '2021-12-09 20:37:53', 'Yulin', 1);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (88, 0, 'Sales Associate', 'Underdosing of angiotensin-converting-enzyme inhibitors', '2021-04-09 17:52:50', 'Yalukou', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (89, 1, 'Graphic Designer', 'Siderosis of eye, right eye', '2022-10-11 21:33:18', 'Dongyangzhen', 12);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (90, 1, 'Analog Circuit Design manager', 'Neonatal candidiasis', '2021-04-21 17:36:57', 'Néa Flogitá', 6);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (91, 0, 'Structural Analysis Engineer', 'Disp fx of med condyle of r tibia, 7thP', '2022-08-25 19:39:47', 'Moyamba', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (92, 1, 'Web Developer III', 'Hallux valgus (acquired), left foot', '2021-06-11 09:29:40', 'Cachada', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (93, 0, 'Assistant Professor', 'Central cord syndrome at C5, subs', '2022-01-20 12:35:21', 'Tarrafal', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (94, 0, 'Desktop Support Technician', 'Dislocation of internal left hip prosthesis', '2021-09-07 05:10:29', 'Marisol', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (95, 0, 'Actuary', 'Nondisp oblique fx shaft of l fibula, 7thF', '2022-04-10 17:36:48', 'Maurole', 5);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (96, 0, 'Assistant Media Planner', 'Malignant neoplasm of anus and anal canal', '2022-01-11 17:26:16', 'Kuršumlija', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (97, 1, 'Human Resources Assistant II', 'Obstructed labor due to other multiple fetuses', '2022-05-22 03:41:40', 'Łanięta', 2);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (98, 1, 'Analog Circuit Design manager', 'Adult and child abuse, neglect and oth maltreat, confirmed', '2022-03-07 13:52:18', 'Stettler', 8);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (99, 1, 'Teacher', 'Disp fx of prox phalanx of unsp fngr, subs for fx w nonunion', '2022-11-08 23:04:24', 'Sumuranyar', 11);
insert into job_offers (id, is_active, job_title, job_description, published_time, location, vacancies) values (100, 1, 'Human Resources Manager', 'Toxic effect of cobra venom, accidental, init', '2022-08-27 14:41:38', 'Ludbreg', 4);

-- COMPANIES - OFFERS

UPDATE job_offers SET COMPANY_ID =66 WHERE id =1;
UPDATE job_offers SET COMPANY_ID =16 WHERE id =2;
UPDATE job_offers SET COMPANY_ID =34 WHERE id =3;
UPDATE job_offers SET COMPANY_ID =64 WHERE id =4;
UPDATE job_offers SET COMPANY_ID =65 WHERE id =5;
UPDATE job_offers SET COMPANY_ID =34 WHERE id =6;
UPDATE job_offers SET COMPANY_ID =67 WHERE id =7;
UPDATE job_offers SET COMPANY_ID =14 WHERE id =8;
UPDATE job_offers SET COMPANY_ID =18 WHERE id =9;
UPDATE job_offers SET COMPANY_ID =20 WHERE id =10;
UPDATE job_offers SET COMPANY_ID =65 WHERE id =11;
UPDATE job_offers SET COMPANY_ID =20 WHERE id =12;
UPDATE job_offers SET COMPANY_ID =61 WHERE id =13;
UPDATE job_offers SET COMPANY_ID =38 WHERE id =14;
UPDATE job_offers SET COMPANY_ID =11 WHERE id =15;
UPDATE job_offers SET COMPANY_ID =11 WHERE id =16;
UPDATE job_offers SET COMPANY_ID =17 WHERE id =17;
UPDATE job_offers SET COMPANY_ID =21 WHERE id =18;
UPDATE job_offers SET COMPANY_ID =8 WHERE id =19;
UPDATE job_offers SET COMPANY_ID =15 WHERE id =20;
UPDATE job_offers SET COMPANY_ID =31 WHERE id =21;
UPDATE job_offers SET COMPANY_ID =39 WHERE id =22;
UPDATE job_offers SET COMPANY_ID =7 WHERE id =23;
UPDATE job_offers SET COMPANY_ID =38 WHERE id =24;
UPDATE job_offers SET COMPANY_ID =54 WHERE id =25;
UPDATE job_offers SET COMPANY_ID =3 WHERE id =26;
UPDATE job_offers SET COMPANY_ID =23 WHERE id =27;
UPDATE job_offers SET COMPANY_ID =41 WHERE id =28;
UPDATE job_offers SET COMPANY_ID =33 WHERE id =29;
UPDATE job_offers SET COMPANY_ID =40 WHERE id =30;
UPDATE job_offers SET COMPANY_ID =3 WHERE id =31;
UPDATE job_offers SET COMPANY_ID =62 WHERE id =32;
UPDATE job_offers SET COMPANY_ID =48 WHERE id =33;
UPDATE job_offers SET COMPANY_ID =40 WHERE id =34;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =35;
UPDATE job_offers SET COMPANY_ID =35 WHERE id =36;
UPDATE job_offers SET COMPANY_ID =50 WHERE id =37;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =38;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =39;
UPDATE job_offers SET COMPANY_ID =60 WHERE id =40;
UPDATE job_offers SET COMPANY_ID =15 WHERE id =41;
UPDATE job_offers SET COMPANY_ID =57 WHERE id =42;
UPDATE job_offers SET COMPANY_ID =40 WHERE id =43;
UPDATE job_offers SET COMPANY_ID =6 WHERE id =44;
UPDATE job_offers SET COMPANY_ID =61 WHERE id =45;
UPDATE job_offers SET COMPANY_ID =12 WHERE id =46;
UPDATE job_offers SET COMPANY_ID =20 WHERE id =47;
UPDATE job_offers SET COMPANY_ID =65 WHERE id =48;
UPDATE job_offers SET COMPANY_ID =33 WHERE id =49;
UPDATE job_offers SET COMPANY_ID =25 WHERE id =50;
UPDATE job_offers SET COMPANY_ID =3 WHERE id =51;
UPDATE job_offers SET COMPANY_ID =62 WHERE id =52;
UPDATE job_offers SET COMPANY_ID =35 WHERE id =53;
UPDATE job_offers SET COMPANY_ID =50 WHERE id =54;
UPDATE job_offers SET COMPANY_ID =61 WHERE id =55;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =56;
UPDATE job_offers SET COMPANY_ID =34 WHERE id =57;
UPDATE job_offers SET COMPANY_ID =8 WHERE id =58;
UPDATE job_offers SET COMPANY_ID =8 WHERE id =59;
UPDATE job_offers SET COMPANY_ID =45 WHERE id =60;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =61;
UPDATE job_offers SET COMPANY_ID =24 WHERE id =62;
UPDATE job_offers SET COMPANY_ID =8 WHERE id =63;
UPDATE job_offers SET COMPANY_ID =40 WHERE id =64;
UPDATE job_offers SET COMPANY_ID =24 WHERE id =65;
UPDATE job_offers SET COMPANY_ID =61 WHERE id =66;
UPDATE job_offers SET COMPANY_ID =41 WHERE id =67;
UPDATE job_offers SET COMPANY_ID =57 WHERE id =68;
UPDATE job_offers SET COMPANY_ID =21 WHERE id =69;
UPDATE job_offers SET COMPANY_ID =47 WHERE id =70;
UPDATE job_offers SET COMPANY_ID =64 WHERE id =71;
UPDATE job_offers SET COMPANY_ID =57 WHERE id =72;
UPDATE job_offers SET COMPANY_ID =61 WHERE id =73;
UPDATE job_offers SET COMPANY_ID =29 WHERE id =74;
UPDATE job_offers SET COMPANY_ID =3 WHERE id =75;
UPDATE job_offers SET COMPANY_ID =38 WHERE id =76;
UPDATE job_offers SET COMPANY_ID =34 WHERE id =77;
UPDATE job_offers SET COMPANY_ID =38 WHERE id =78;
UPDATE job_offers SET COMPANY_ID =60 WHERE id =79;
UPDATE job_offers SET COMPANY_ID =17 WHERE id =80;
UPDATE job_offers SET COMPANY_ID =27 WHERE id =81;
UPDATE job_offers SET COMPANY_ID =52 WHERE id =82;
UPDATE job_offers SET COMPANY_ID =52 WHERE id =83;
UPDATE job_offers SET COMPANY_ID =3 WHERE id =84;
UPDATE job_offers SET COMPANY_ID =65 WHERE id =85;
UPDATE job_offers SET COMPANY_ID =5 WHERE id =86;
UPDATE job_offers SET COMPANY_ID =52 WHERE id =87;
UPDATE job_offers SET COMPANY_ID =62 WHERE id =88;
UPDATE job_offers SET COMPANY_ID =50 WHERE id =89;
UPDATE job_offers SET COMPANY_ID =12 WHERE id =90;
UPDATE job_offers SET COMPANY_ID =28 WHERE id =91;
UPDATE job_offers SET COMPANY_ID =54 WHERE id =92;
UPDATE job_offers SET COMPANY_ID =49 WHERE id =93;
UPDATE job_offers SET COMPANY_ID =49 WHERE id =94;
UPDATE job_offers SET COMPANY_ID =34 WHERE id =95;
UPDATE job_offers SET COMPANY_ID =56 WHERE id =96;
UPDATE job_offers SET COMPANY_ID =22 WHERE id =97;
UPDATE job_offers SET COMPANY_ID =7 WHERE id =98;
UPDATE job_offers SET COMPANY_ID =26 WHERE id =99;
UPDATE job_offers SET COMPANY_ID =44 WHERE id =100;

-- CANDIDATES

insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Georgianna', 'Clampett', 'gclampett0@timesonline.co.uk', 'F', '463 Twin Pines Parkway', 'Xifangcheng');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Salvatore', 'Nelthropp', 'snelthropp1@clickbank.net', 'M', '242 Moland Road', 'Tetebatu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Guenna', 'Draisey', 'gdraisey2@is.gd', 'F', '38051 Rieder Park', 'Ústí nad Labem');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Derry', 'Annesley', 'dannesley3@posterous.com', 'M', '224 Corben Hill', 'Murowana Goślina');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Erskine', 'Bode', 'ebode4@microsoft.com', 'M', '0209 Kropf Point', 'El Retorno');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Fabio', 'Toupe', 'ftoupe5@kickstarter.com', 'M', '2458 Erie Junction', 'Gorobinci');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Lock', 'Cripin', 'lcripin6@umn.edu', 'M', '6 Little Fleur Alley', 'Dzüyl');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Kristoffer', 'Krolak', 'kkrolak7@statcounter.com', 'M', '290 Forster Terrace', 'Adolfo Ruiz Cortines');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Robbie', 'Vellender', 'rvellender8@posterous.com', 'M', '99 Granby Plaza', 'Serikbuya');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Everett', 'Wigfield', 'ewigfield9@youtu.be', 'M', '877 Carpenter Way', 'Tanshi');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Scarlett', 'Rodden', 'sroddena@ucoz.com', 'F', '14 Cascade Junction', 'Dallas');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Hermy', 'Cancutt', 'hcancuttb@google.com.br', 'M', '832 Westerfield Terrace', 'Donglai');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Jasmina', 'Bortoloni', 'jbortolonic@engadget.com', 'F', '39292 Graceland Lane', 'Nurmijärvi');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Devi', 'Hakey', 'dhakeyd@privacy.gov.au', 'F', '930 Sachtjen Street', 'Idvor');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Jeanette', 'Bedford', 'jbedforde@surveymonkey.com', 'F', '299 Homewood Terrace', 'Panji');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Hadria', 'Rodenborch', 'hrodenborchf@wiley.com', 'F', '7 Lerdahl Avenue', 'Shalushka');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Darcy', 'Messam', 'dmessamg@ow.ly', 'F', '28887 Fulton Junction', 'Costa Rica');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Lorne', 'Sackes', 'lsackesh@jigsy.com', 'M', '824 Manufacturers Avenue', 'Kushovë');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Rikki', 'Bisley', 'rbisleyi@yellowbook.com', 'F', '827 Larry Avenue', 'Washington');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Domini', 'Kalkofer', 'dkalkoferj@dyndns.org', 'F', '73736 Blaine Plaza', 'Ipoh');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Ilsa', 'McVey', 'imcveyk@bbb.org', 'F', '248 Burrows Drive', 'General Alvear');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Jordana', 'Gebbie', 'jgebbiel@sciencedirect.com', 'F', '24642 Eggendart Junction', 'Jieshou');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Yul', 'Rooney', 'yrooneym@washington.edu', 'M', '62745 Lukken Alley', 'Walakeri');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Zilvia', 'Pyner', 'zpynern@digg.com', 'F', '0 Fallview Junction', 'Jawand');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Allan', 'Kubes', 'akubeso@hatena.ne.jp', 'M', '73625 High Crossing Plaza', 'Katiola');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Domeniga', 'MacLucais', 'dmaclucaisp@businesswire.com', 'F', '18733 Claremont Junction', 'Uba');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Casi', 'Longdon', 'clongdonq@usa.gov', 'F', '5636 Clemons Alley', 'Charlottesville');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Tammie', 'Upex', 'tupexr@ask.com', 'M', '424 Moose Road', 'Vuka');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Tam', 'Nesey', 'tneseys@w3.org', 'M', '5 Almo Junction', 'Shanhe');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Antoine', 'Iapico', 'aiapicot@ed.gov', 'M', '75975 2nd Center', 'Cigenca');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Demetrius', 'Kivlin', 'dkivlinu@google.de', 'M', '25 School Parkway', 'Nacimiento');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Dalton', 'Lumber', 'dlumberv@aol.com', 'M', '91 Lindbergh Circle', 'Tiandiba');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Janice', 'Twist', 'jtwistw@bloglines.com', 'F', '6 Scott Point', 'Saint-Cloud');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Emili', 'Barde', 'ebardex@patch.com', 'F', '331 Harbort Court', 'Huyunxiang');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Rodolph', 'Clewlow', 'rclewlowy@loc.gov', 'M', '99 Clove Way', 'Vynohradivka');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Scottie', 'Passfield', 'spassfieldz@house.gov', 'M', '36 Clarendon Plaza', 'Santa Tecla');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Ania', 'Sprowell', 'asprowell10@prnewswire.com', 'F', '6 Di Loreto Hill', 'Heerlen');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Meridel', 'Stoade', 'mstoade11@prlog.org', 'F', '55064 Brentwood Pass', 'Nioro');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Courtnay', 'Lanham', 'clanham12@nationalgeographic.com', 'M', '19669 Menomonie Lane', 'Santo Tomas');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Kristi', 'Meredyth', 'kmeredyth13@state.tx.us', 'F', '35 Dixon Avenue', 'Al Hāshimīyah');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Glynn', 'Luebbert', 'gluebbert14@php.net', 'M', '6 Arrowood Street', 'Yên Lập');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Pincus', 'Vedeshkin', 'pvedeshkin15@nature.com', 'M', '7172 Texas Street', 'Jablonec nad Nisou');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Alex', 'Benoiton', 'abenoiton16@columbia.edu', 'F', '52018 Logan Point', 'Trondheim');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Bradan', 'Arnli', 'barnli17@unc.edu', 'M', '43993 Cody Point', 'Yunxi');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Darius', 'Passion', 'dpassion18@unicef.org', 'M', '2481 Paget Lane', 'Desakolot');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Phebe', 'Fieller', 'pfieller19@mysql.com', 'F', '6022 Montana Court', 'Dukuh Kaler');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Sebastiano', 'Beecker', 'sbeecker1a@bloomberg.com', 'M', '9 Nelson Place', 'Tādif');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Karylin', 'Walbrun', 'kwalbrun1b@mlb.com', 'F', '0 Meadow Valley Junction', 'Peliyagoda');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Alejoa', 'Colmore', 'acolmore1c@altervista.org', 'M', '26233 Nevada Court', 'Sedan');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Thadeus', 'Kees', 'tkees1d@state.tx.us', 'M', '334 Pennsylvania Hill', 'Laoqiao');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Tam', 'Dawtrey', 'tdawtrey1e@seattletimes.com', 'M', '2002 Pine View Way', 'Stare Miasto');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Goddard', 'Camblin', 'gcamblin1f@go.com', 'M', '0925 Northport Alley', 'Taguisa');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Orsola', 'Gosdin', 'ogosdin1g@abc.net.au', 'F', '7 Atwood Park', 'Sala');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Jimmy', 'Hanney', 'jhanney1h@live.com', 'M', '239 Jackson Road', 'Viejo Daan Banua');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Biddie', 'Lawday', 'blawday1i@myspace.com', 'F', '4730 Waubesa Terrace', 'Sirindhorn');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Bev', 'Wilprecht', 'bwilprecht1j@marriott.com', 'M', '8 Melrose Terrace', 'General La Madrid');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Elwin', 'Langford', 'elangford1k@freewebs.com', 'M', '8208 Linden Crossing', 'Zoumachang');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Mitchael', 'Warbey', 'mwarbey1l@techcrunch.com', 'M', '2 Clarendon Plaza', 'Zgornje Pirniče');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Roderigo', 'Jouannin', 'rjouannin1m@un.org', 'M', '4797 Sage Lane', 'Těšetice');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Allsun', 'Cullimore', 'acullimore1n@github.com', 'F', '56836 Eastwood Alley', 'Bishan');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Clemmie', 'Crowcombe', 'ccrowcombe1o@mtv.com', 'F', '4605 Blackbird Park', 'Portel');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Maura', 'Chesson', 'mchesson1p@wunderground.com', 'F', '6 Lake View Avenue', 'Dawangzhuang');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Bail', 'Dootson', 'bdootson1q@gmpg.org', 'M', '5 Maryland Avenue', 'Pokrovskoye');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Ros', 'Tregona', 'rtregona1r@purevolume.com', 'F', '98 Shasta Junction', 'Ekenäs');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Gayler', 'Girvin', 'ggirvin1s@blogger.com', 'M', '1 Shopko Court', 'Peroguarda');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Merwin', 'Bickerton', 'mbickerton1t@squidoo.com', 'M', '46974 Arapahoe Plaza', 'Tembladera');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Garek', 'Mathews', 'gmathews1u@booking.com', 'M', '946 Lakeland Road', 'Liuqu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Valera', 'O''Cannon', 'vocannon1v@noaa.gov', 'F', '1226 Farmco Avenue', 'Miras');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Thorin', 'Farfull', 'tfarfull1w@narod.ru', 'M', '702 Village Circle', 'Lapuyan');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Alfreda', 'Balam', 'abalam1x@edublogs.org', 'F', '182 Homewood Street', 'Passos');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Vinny', 'MacKimm', 'vmackimm1y@bloglovin.com', 'M', '038 Mcguire Terrace', 'Bopu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Dyana', 'Dearnley', 'ddearnley1z@irs.gov', 'F', '32153 Bay Place', 'Solnechnogorsk');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Clarissa', 'Butler', 'cbutler20@wired.com', 'F', '83 Sage Court', 'Piteå');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Merla', 'Masic', 'mmasic21@upenn.edu', 'F', '47 Cody Junction', 'Xiting');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Myron', 'Rickasse', 'mrickasse22@rediff.com', 'M', '89154 Del Mar Avenue', 'Kachkanar');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Dore', 'Gebuhr', 'dgebuhr23@thetimes.co.uk', 'M', '16938 Fairfield Plaza', 'Jiaohu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Lamont', 'O''Doohaine', 'lodoohaine24@ca.gov', 'M', '86038 Glacier Hill Trail', 'Plagiári');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Alwin', 'Pilmore', 'apilmore25@bravesites.com', 'M', '2 Evergreen Circle', 'Kayanza');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Jud', 'Leehane', 'jleehane26@kickstarter.com', 'M', '789 Dakota Terrace', 'Su’ao');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Umeko', 'Warnes', 'uwarnes27@hostgator.com', 'F', '3 Canary Court', 'Ntobo');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Deloria', 'Grioli', 'dgrioli28@pen.io', 'F', '5 Cordelia Circle', 'Rtyně v Podkrkonoší');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Ellery', 'Chancellor', 'echancellor29@woothemes.com', 'M', '2533 Amoth Hill', 'Krajan Curahcotok');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Giffy', 'Garforth', 'ggarforth2a@gizmodo.com', 'M', '66 Fordem Center', 'Mimbaan Timur');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Tuckie', 'Restill', 'trestill2b@nsw.gov.au', 'M', '6489 Katie Avenue', 'Qingshuitang');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Eirena', 'Dempsey', 'edempsey2c@icq.com', 'F', '138 Heath Parkway', 'San Borja');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Foss', 'De la Yglesia', 'fdelayglesia2d@youku.com', 'M', '9366 Jay Drive', 'Xiaolong');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Madlin', 'Kleinert', 'mkleinert2e@mac.com', 'F', '66846 Hoard Place', 'Dístomo');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Immanuel', 'Philipart', 'iphilipart2f@plala.or.jp', 'M', '65751 Becker Place', 'Iracemápolis');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Paten', 'Callington', 'pcallington2g@opera.com', 'M', '02376 Blackbird Pass', 'Deskáti');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Johnath', 'Ledley', 'jledley2h@scribd.com', 'F', '148 Badeau Way', 'Luoshe');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Amabelle', 'Bligh', 'abligh2i@marriott.com', 'F', '5406 Hagan Pass', 'Ginir');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Hagan', 'Jakeman', 'hjakeman2j@sitemeter.com', 'M', '7 Union Court', 'Pingyao');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Meredithe', 'Tewkesberrie', 'mtewkesberrie2k@webmd.com', 'F', '38 Portage Trail', 'Bethel Town');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Dareen', 'Kirsopp', 'dkirsopp2l@fda.gov', 'F', '73375 Dexter Place', 'Niu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Arleyne', 'Brolly', 'abrolly2m@deliciousdays.com', 'F', '00 Messerschmidt Road', 'Luntas');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Caterina', 'Oki', 'coki2n@stanford.edu', 'F', '9594 Katie Point', 'Beberon');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Nathan', 'Rodenborch', 'nrodenborch2o@stanford.edu', 'M', '9 Nelson Circle', 'Atakpamé');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Emma', 'Swiffen', 'eswiffen2p@jugem.jp', 'F', '1 5th Junction', 'Aksu');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (1, 'Mayer', 'Rraundl', 'mrraundl2q@typepad.com', 'M', '0879 Morrow Drive', 'Ozurgeti');
insert into candidates (is_open_to_work, first_name, last_name, email, gender, street, location) values (0, 'Adrien', 'Jacob', 'ajacob2r@irs.gov', 'M', '06889 Weeping Birch Parkway', 'Domartang');

-- CANDIDATES' CATEGORIES

insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (85, 'hierarchy');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (17, 'modular');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (66, 'focus group');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (31, 'Right-sized');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (53, 'array');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (5, 'Integrated');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (71, 'discrete');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (18, 'middleware');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (41, 'middleware');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (2, 'User-friendly');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (25, 'User-friendly');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (56, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (64, 'composite');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (19, 'array');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (21, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (56, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (96, 'homogeneous');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (95, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (83, 'value-added');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (6, 'throughput');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (63, 'Integrated');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (26, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (85, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (95, 'Progressive');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (36, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (2, 'throughput');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (69, 'homogeneous');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (6, 'hierarchy');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (82, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (57, 'Future-proofed');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (96, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (2, 'array');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (25, 'throughput');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (80, 'migration');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (44, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (50, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (8, 'knowledge user');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (14, 'Progressive');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (90, 'motivating');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (13, 'Progressive');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (16, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (98, 'Graphic Interface');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (16, 'motivating');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (90, 'motivating');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (2, 'Progressive');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (10, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (75, 'Progressive');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (18, 'homogeneous');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (66, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (51, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (47, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (71, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (34, 'migration');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (2, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (25, 'throughput');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (85, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (74, 'Future-proofed');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (24, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (40, 'Right-sized');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (22, 'motivating');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (51, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (29, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (55, 'homogeneous');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (23, 'throughput');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (31, 'time-frame');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (87, 'migration');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (12, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (46, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (47, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (64, 'homogeneous');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (19, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (53, 'knowledge base');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (90, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (26, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (30, 'focus group');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (41, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (52, 'Future-proofed');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (48, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (29, 'full-range');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (44, '6th generation');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (25, 'Persevering');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (3, 'Integrated');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (62, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (74, 'hierarchy');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (36, 'dynamic');
insert into CANDIDATE_CATEGORY   (CANDIDATES_ID, CATEGORY_CATEGORY) values (94, 'motivating');


